// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_sksbLYbZUmU5aB-BOGeOz__YSbvVNo',
    appId: '1:589766530196:web:e6817bdf34e7820e031081',
    messagingSenderId: '589766530196',
    projectId: 'international-women-s-day-25',
    authDomain: 'international-women-s-day-25.firebaseapp.com',
    storageBucket: 'international-women-s-day-25.firebasestorage.app',
    measurementId: 'G-M0WM6VKLW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1bzE1buVVIU-oIGnuhjq3rCjCg6JURc',
    appId: '1:589766530196:android:f7ed9f1f7f3259eb031081',
    messagingSenderId: '589766530196',
    projectId: 'international-women-s-day-25',
    storageBucket: 'international-women-s-day-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiWCx18crGuVquSURabUSR_jstPzjaPA',
    appId: '1:589766530196:ios:e765df47ed86688f031081',
    messagingSenderId: '589766530196',
    projectId: 'international-women-s-day-25',
    storageBucket: 'international-women-s-day-25.firebasestorage.app',
    iosClientId: '589766530196-q4004khvh91793iia38qplc0e09qqfj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.iwdAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiWCx18crGuVquSURabUSR_jstPzjaPA',
    appId: '1:589766530196:ios:e765df47ed86688f031081',
    messagingSenderId: '589766530196',
    projectId: 'international-women-s-day-25',
    storageBucket: 'international-women-s-day-25.firebasestorage.app',
    iosClientId: '589766530196-q4004khvh91793iia38qplc0e09qqfj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.iwdAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB_sksbLYbZUmU5aB-BOGeOz__YSbvVNo',
    appId: '1:589766530196:web:23a22ed156a25760031081',
    messagingSenderId: '589766530196',
    projectId: 'international-women-s-day-25',
    authDomain: 'international-women-s-day-25.firebaseapp.com',
    storageBucket: 'international-women-s-day-25.firebasestorage.app',
    measurementId: 'G-T4QE046H44',
  );
}
